name: KB-GUI

# Controls when the action will run. 
on: 
  push:
    branches: [develop]
  pull_request:
    branches: [main,develop]
     
  # Allows this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
       
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        python-version: [3.6, 3.7, 3.8, 3.9]
        
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; else pip install -r requirements.txt; fi
    - name: Lint with flake8 if on a develop or feature branch
      if: github.ref != 'refs/remotes/origin/main'
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        codespell . --skip="*.drawio,./.git,*postman*" --ignore-words-list=hist --quiet-level=2
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #- name: Test with pytest
    #  if: github.ref != 'refs/remotes/origin/main'
    #  run: |
    #    pytest

